export const TOGGLE_LEFT_HAND_NAV = 'TOGGLE_LEFT_HAND_NAV'

export const GET_PROFILE_AND_DASHBOARDS = 'GET_PROFILE_AND_DASHBOARDS'
export const GET_PROFILE_AND_DASHBOARDS_SUCCESS = 'GET_PROFILE_AND_DASHBOARDS_SUCCESS'
export const GET_PROFILE_AND_DASHBOARDS_ERROR = 'GET_PROFILE_AND_DASHBOARDS_ERROR'

export const GET_DASHBOARD_TOKEN = 'GET_DASHBOARD_TOKEN'
export const GET_DASHBOARD_TOKEN_SUCCESS = 'GET_DASHBOARD_TOKEN_SUCCESS'
export const GET_DASHBOARD_TOKEN_ERROR = 'GET_DASHBOARD_TOKEN_ERROR'

export const GET_TABLEAU_API_FOR_DASHBOARD = 'GET_TABLEAU_API_FOR_DASHBOARD'
export const SET_WORKBOOK_VALUES = 'SET_WORKBOOK_VALUES'

export const ADD_DASHBOARD_VIEW = 'ADD_DASHBOARD_VIEW'
export const REMOVE_DASHBOARD_VIEW = 'REMOVE_DASHBOARD_VIEW'
export const SET_DEFAULT_DASHBOARD_VIEW = 'SET_DEFAULT_DASHBOARD_VIEW'
export const SHOW_DASHBOARD_VIEW = 'SHOW_DASHBOARD_VIEW'

export const SET_DASHBOARD_FILTER = 'SET_DASHBOARD_FILTER'

export const SHOW_HEADER_MODULES = 'SHOW_HEADER_MODULES'
export const HIDE_HEADER_MODULES = 'HIDE_HEADER_MODULES'
