export const SET_PROFILE = 'SET_PROFILE'

export const TOGGLE_LEFT_HAND_NAV = 'TOGGLE_LEFT_HAND_NAV'

export const SELECT_DASHBOARD = 'SELECT_DASHBOARD'
export const GET_DASHBOARDS_NAMES = 'GET_DASHBOARDS_NAMES'
export const GET_DASHBOARDS_NAMES_SUCCESS = 'GET_DASHBOARDS_NAMES_SUCCESS'
export const GET_DASHBOARDS_NAMES_ERROR = 'GET_DASHBOARDS_NAMES_ERROR'
export const GET_DASHBOARD_TOKEN = 'GET_DASHBOARD_TOKEN'
export const GET_DASHBOARD_TOKEN_SUCCESS = 'GET_DASHBOARD_TOKEN_SUCCESS'
export const GET_DASHBOARD_TOKEN_ERROR = 'GET_DASHBOARD_TOKEN_ERROR'

export const SHOW_HEADER_MODULES = 'SHOW_HEADER_MODULES'
export const HIDE_HEADER_MODULES = 'HIDE_HEADER_MODULES'

