/* global CONFIG */
export const CP_ADMIN_HOST = CONFIG.CP_ADMIN_HOST
export const CP_ANALYTICS_HOST = CONFIG.CP_ANALYTICS_HOST
export const CP_ANALYTICS_BACKEND = CONFIG.CP_ANALYTICS_BACKEND
export const TABLEAUT_HOST = CONFIG.TABLEAU_HOST
export const TABLEAU_GATEWAY_API = CONFIG.TABLEAU_GATEWAY_API
