_templates: 
  - &ecr-auth
    ecr#v2.1.0:
      login: true
      account_ids: "896069866492"
      no-include-email: true
      region: "eu-west-1"

steps:
  - label: ":docker: Build & Publish"
    plugins:
      - *ecr-auth
    command: |
      make publish

  - wait

  - label: ":bomb: Tests"
    plugins:
      - *ecr-auth
    command: |
      make test

  - block: ":rocket: Deploy to staging! :chicken:"
    fields:
      - select: "I'm deploying to STAGING!"
        key: "unleash-the-chicken"
        default: "yes"
        options:
          - label: ":chicken: yes, release the chicken! :rooster:"
            value: "yes"


  - label: ":helm: :arrow_right: :k8s: staging"
    plugins:
      - *ecr-auth
    command: |
      make deploy
    env:
      ENV: staging

  - block: ":rocket: Deploy to production!"
    fields:
      - select: "I'm sure, I'm deploying to PRODUCTION!"
        key: "unleash-the-dragon"
        options:
          - label: ":dragon_face: yes, unleash the dragon! :dragon:"
            value: "yes"
    branches: 'master'

  - label: ":docker: Tag Image"
    plugins:
      - *ecr-auth
    command: |
      make tag-prod-image
    branches: 'master'
    
  - wait

  - label: ":helm: :arrow_right: :k8s: production"
    plugins:
      - *ecr-auth
    command: |
      make deploy
    env:
      ENV: production
    branches: 'master'
